export const GET_USERS = "GET_USERS";
export const GET_FAVORITES = "GET_FAVORITES";
export const FILTER_BY_DIET_FAVORITE = "FILTER_BY_DIET_FAVORITE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";